version: "3.3"
services:
  lab_web:
    container_name: lab_web
    image: nginx:1.15-alpine
    links:
      - lab_phpfpm
    ports:
      - "80:80"
    volumes:
      - ./docker/logs/access.log:/var/log/nginx/lab_access.log:delegated
      - ./docker/logs/error.log:/var/log/nginx/lab_error.log:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./:/var/www/html/public:delegated
    environment:
      - VIRTUAL_HOST=lab.local
    networks:
      - app_network

  lab_phpfpm:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: lab_phpfpm
    ports:
      - "9000:9000"
    links:
      - lab_mysql
    volumes:
      - ./:/var/www/html/public:delegated
    networks:
      - app_network

  lab_mysql:
    image: "mysql:5.5"
    container_name: lab_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_DATABASE}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network

  lab_phpmyadmin:
    container_name: lab_phpmyadmin
    image: "phpmyadmin/phpmyadmin:latest"
    restart: always
    links:
      - lab_mysql
    ports:
      - "8001:80"
    environment:
      - PMA_HOSTS=lab_mysql
    networks:
      - app_network

    adminer:
      container_name: adminer
      image: adminer:latest
      links:
        - lab_mysql
      environment:
        - ADMINER_DEFAULT_SERVER=lab_mysql
      ports:
        - 8002:8080
      networks:
        - app_network

# If have bellow error then create a network. : docker network create app_network
# Example ERROR: Network app_network declared as external, but could not be found. Please create the network manually using `docker network create app_network` and try again.
networks:
  app_network:
    external: true
